version: '3.3'
services:
  app:
    build:
      dockerfile: Dockerfile
    image: biker_management
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'biker_management_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USERNAME}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      # localhost:9000
      - 9000:8080
# Names our volume
volumes:
  my-db:
