create table products (
    price float(24) not null, product_id integer generated by default as identity, quantity integer not null, store_id integer, name varchar(255), primary key (product_id)
);

create table stores (
    store_id integer not null, city varchar(255), country varchar(255), name varchar(255), post_code varchar(255), state varchar(255), street varchar(255), primary key (store_id)
);

alter table if exists products
add constraint FKgcyffheofvmy2x5l78xam63mc foreign key (store_id) references stores;