create table orders (
    order_id integer generated by default as identity, product_id integer unique, status varchar(255), eta date, vat float(24), total_cost float(24), customer_id integer, store_id integer, street varchar(255), city varchar(255), state varchar(255), post_code varchar(255), country varchar(255), biker_id integer, rating integer, review varchar(255), primary key (order_id)
);

alter table if exists orders
add constraint FKaw3syk90oe0615hben2ta36i0 foreign key (biker_id) references bikers;

alter table if exists orders
add constraint FKpxtb8awmi0dk6smoh2vp1litg foreign key (customer_id) references customers;

alter table if exists orders
add constraint FKnqkwhwveegs6ne9ra90y1gq0e foreign key (store_id) references stores;

alter table if exists orders
add constraint FKkp5k52qtiygd8jkag4hayd0qg foreign key (product_id) references products;